### ISSUE TITLE
'percy-storybook@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by squidsoup** [percy/storybook-action#6]
When running `percy/storybook-action@v0.1.3`

```
/usr/local/bin/npx percy-storybook
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/percy-storybook - Not found
npm ERR! 404 
npm ERR! 404  'percy-storybook@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-03-10T06_04_09_392Z-debug.log
Install for [ 'percy-storybook@latest' ] failed with code 1
```

From what I can gather this should be `@percy/storybook` rather than `percy-storybook`?

**Comment by Robdel12** [comment]
Hey @squidsoup, thanks for the report! This shouldn't fail if you have `@percy/storybook` installed as a dependency in the project. `percy-storybook` is the executables name, which should be found if installed.

**Comment by squidsoup** [comment]
> Hey @squidsoup, thanks for the report! This shouldn't fail if you have `@percy/storybook` installed as a dependency in the project. `percy-storybook` is the executables name, which should be found if installed.

Oh apologies, that makes sense. Perhaps an update to the storybook-action docs to make it clear that dependency is required?

**Comment by Robdel12** [comment]
@squidsoup Gotcha! We try to highlight at the top of the docs that CI setup should come _after_ the SDK is setup: 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/2072894/76546448-7e2d8200-6459-11ea-9b8e-9e1b7a8ba945.png">
